### ISSUE TITLE
Make the words be stored in a file, and randomly picked from there.

### ISSUE THREAD

**Issue by Robby-cell** [Robby-cell/terminal-hangman#1]

**Comment by TeenaBatra** [comment]
Hi @Robby-cell, I worked on this same game, dropping the link if you wanna have a look: https://github.com/TeenaBatra/Hangman_Game, I have created a separate file(hangman_word.py) which contains all the words in the python list and imported that in the main.py to randomly pick the word from that list of words.

**Comment by JefvdA** [comment]
Certainly a good and easy way of doing it, as @TeenaBatra mentioned. I think it's a matter of what @Robby-cell wants to do, as creating a simple .txt file is just a little easier for people to add their own words if they don't know python, also being able to just place a word on a line instead of having the python array syntax is a plus aswell.

But still, both an option :)
